services: 
  mailserver: 
    image: docker.io/mailserver/docker-mailserver:latest 
    container_name: mailserver 
    hostname: mail-server
    domainname: datasense-relay.koyeb.app 
    ports: 
      - "25:25" 
      - "587:587" 
      - "465:465" 
    volumes: 
      - ./docker-data/dms/mail-data/:/var/mail/ 
      - ./docker-data/dms/mail-state/:/var/mail-state/ 
      - ./docker-data/dms/mail-logs/:/var/log/mail/ 
      - ./docker-data/dms/config/:/tmp/docker-mailserver/ 
      - ./docker-data/nginx-proxy/certs/:/etc/letsencrypt/ 
      - /etc/localtime:/etc/localtime:ro 
    environment: 
      - ENABLE_FAIL2BAN=1 
      - SSL_TYPE=letsencrypt 
      - PERMIT_DOCKER=network 
      - ONE_DIR=1 
      - ENABLE_POSTGREY=0 
      - ENABLE_CLAMAV=0 
      - ENABLE_SPAMASSASSIN=0 
      - SPOOF_PROTECTION=0 
    cap_add: 
      - NET_ADMIN 
      - SYS_PTRACE
